[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.python]
default_packages_file = "base-requirements.txt"

[tools]
# we can activate once 3.14 is officially released
#python = { version = "3.14" }
typst = "0.14.2"


[env]
_.python.venv = { path = "venv", create = true, python = "3.14" } # use a specific python version
MODEL_WEIGHTS_PATH="{{ config_root }}/out/deep_learning/run_20260504_192451/checkpoints/model_20260504_192451_600.bpk"
TYPST_ROOT="{{ config_root }}"
TYPST_FONT_PATHS="{{ config_root }}/resources/fonts/"

[tasks.install_dependencies]
run = "pip install -r requirements.txt -e ."

[tasks.compile_dependencies]
run = "pip-compile -o requirements.txt"
depends_post = ["install_dependencies"]

[tasks."run:genetic_evolution"]
dir = "{{ config_root }}"
run = "cargo run --release --manifest-path scripts/radiate_config_optimizer/Cargo.toml"

[tasks."run:graph_deeplearning"]
dir = "{{ config_root }}"
run = "cargo run --release --package graph_deeplearning"
