[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.python]
default_packages_file = "base-requirements.txt"

[tools]
# we can activate once 3.14 is officially released
#python = { version = "3.14" }
typst = "0.14.2"


[env]
_.python.venv = { path = "venv", create = true, python = "3.14" } # use a specific python version
MODEL_WEIGHTS_PATH="{{ config_root }}/out/deep_learning/run_20260519_105148/checkpoints/model_20260519_105148_1300.bpk"
TYPST_ROOT="{{ config_root }}"
TYPST_FONT_PATHS="{{ config_root }}/resources/fonts/"
TENSORBOARD_LOG_DIR="{{ config_root }}/out/tensorboard-logs"

[tasks."fix:rust"]
run = "cargo clippy --fix"

[tasks."fmt:rust"]
run = "cargo fmt --all"

[tasks."install:pip-dependencies"]
run = "pip install -e ."

[tasks."compile:pip-dependencies"]
run = "pip-compile -o requirements.txt"
depends_post = ["install:pip-dependencies"]

[tasks."run:gui"]
dir = "{{ config_root }}"
run = "python -m plagiarinator.gui"

[tasks."run:cli"]
dir = "{{ config_root }}"
raw = true
raw_args = true
run = "python -m plagiarinator.cli"

[tasks."run:genetic_evolution"]
dir = "{{ config_root }}"
run = "cargo run --release --manifest-path scripts/radiate_config_optimizer/Cargo.toml"

[tasks."run:graph_deeplearning"]
dir = "{{ config_root }}"
run = "cargo run --release --package graph_deeplearning --bin graph_deeplearning"

[tasks."build:graph_inference"]
dir = "{{ config_root }}"
run = "cargo build --release --package graph_deeplearning --bin run_inference"

[tasks."run:graph_validation"]
dir = "{{ config_root }}"
run = "cargo run --release --package graph_deeplearning --bin run_validation"

[tasks."run:tensorboard"]
description = "Run TensorBoard to visualize the training progress"
tools."pipx:tensorboard" = "latest"
dir = "{{ config_root }}"
raw = true
raw_args = true
run = "tensorboard --bind_all --logdir {{ env.TENSORBOARD_LOG_DIR }}"
